import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
// Run the actual hero effect against a deterministic media element and clock.
function heroHarness({reduced=false,mobile=true,blocked=false}={}){
 let now=0,id=0,cleanup,intersection,playCalls=0;const frames=new Map(),timers=new Map(),states=[];
 const section=new EventTarget(),document=new EventTarget(),window=new EventTarget(),media=new EventTarget();
 document.hidden=false;media.matches=reduced;let time=0;
 const video=new EventTarget();Object.assign(video,{readyState:0,duration:8,seeking:false,paused:true,src:'',playbackRate:1,closest:()=>section,load(){},pause(){this.paused=true},play(){playCalls++;if(blocked)return Promise.reject(new Error("Autoplay denied"));this.paused=false;return Promise.resolve()},getAttribute(k){return this[k]||null},removeAttribute(k){this[k]=''}});
 Object.defineProperty(video,'currentTime',{get:()=>time,set:v=>{time=v;video.seeking=true;video.readyState=1}});
 const react={useRef:()=>({current:video}),useState:v=>{const n=states.length;states.push(v);return[v,next=>states[n]=typeof next==='function'?next(states[n]):next]},useEffect:fn=>{cleanup=fn()}};
 const code=ts.transpileModule(readFileSync(new URL('../app/hero-film.tsx',import.meta.url),'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 const context={exports:{},require:name=>name==='react'?react:{jsx:()=>null,jsxs:()=>null},document,window,matchMedia:query=>query.includes('reduced')?media:{matches:mobile},performance:{now:()=>now},requestAnimationFrame:fn=>{frames.set(++id,fn);return id},cancelAnimationFrame:key=>frames.delete(key),setTimeout:(fn,delay)=>{timers.set(++id,{fn,at:now+delay});return id},clearTimeout:key=>timers.delete(key),IntersectionObserver:class{constructor(callback){intersection=callback}observe(){}disconnect(){}}};
 vm.runInNewContext(code,context);context.exports.default();
 const advance=ms=>{now+=ms;for(const [key,t]of[...timers])if(t.at<=now){timers.delete(key);t.fn()}for(const[key,fn]of[...frames]){frames.delete(key);fn(now)}};
 return {video,states,frames,timers,advance,cleanup,media,document,window,get playCalls(){return playCalls},at(value){time=value},intersect(value){intersection([{isIntersecting:value}])},ready(){video.readyState=4;video.seeking=false;video.dispatchEvent(new Event('loadeddata'))},seeked(){video.readyState=4;video.seeking=false;video.dispatchEvent(new Event('seeked'))},progress(value){const event=new Event('hero-film-progress');event.detail=value;section.dispatchEvent(event)}};
}
test('hero selects lightweight mobile footage and falls back on slow loading, then recovers',()=>{const h=heroHarness();assert.match(h.video.src,/-mobile.mp4$/);h.advance(5001);assert.equal(h.states[1],true);h.ready();assert.equal(h.states[0],true);assert.equal(h.states[1],false);h.cleanup();assert.equal(h.frames.size,0);assert.equal(h.timers.size,0)});
test('opening autoplays faster, holds the final second, then scroll finishes without a seek or replay',async()=>{const h=heroHarness();h.ready();await Promise.resolve();assert.equal(h.video.paused,false);assert.equal(h.video.autoplay,true);assert.equal(h.video.loop,false);assert.equal(h.video.muted,true);assert.equal(h.video.defaultMuted,true);assert.equal(h.video.playsInline,true);assert.equal(h.video.controls,false);assert.equal(h.video.playbackRate,1);h.at(6.8);h.advance(40);assert.equal(h.video.paused,true);assert.equal(h.frames.size,0);h.progress(.05);assert.equal(h.video.currentTime,6.8);assert.equal(h.video.seeking,false);assert.equal(h.video.paused,false);assert.equal(h.video.playbackRate,1.2);await Promise.resolve();h.at(7.98);h.advance(40);assert.equal(h.video.paused,true);const calls=h.playCalls;h.progress(0);h.progress(1);h.window.dispatchEvent(new Event('touchstart'));h.intersect(false);h.intersect(true);assert.equal(h.video.currentTime,7.98);assert.equal(h.video.paused,true);assert.equal(h.playCalls,calls);assert.equal(h.frames.size,0);h.cleanup()});
test('early and reverse scrolling never jump, rewind, or restart the opening',async()=>{const h=heroHarness();h.ready();await Promise.resolve();h.at(.6);for(const p of [.1,.9,.2,1,0])h.progress(p);assert.equal(h.video.currentTime,.6);assert.equal(h.video.seeking,false);assert.equal(h.video.paused,false);assert.equal(h.playCalls,1);h.cleanup()});
test('blocked autoplay advances the same video with one outstanding seek and recovers from a slow decode',async()=>{const h=heroHarness({blocked:true});h.ready();await Promise.resolve();await Promise.resolve();h.advance(40);h.advance(40);const time=h.video.currentTime;assert.ok(time>0);assert.equal(h.video.seeking,true);h.advance(100);assert.equal(h.video.currentTime,time);h.advance(1501);assert.equal(h.states[1],true);h.seeked();h.advance(40);assert.ok(h.video.currentTime>time);assert.equal(h.states[1],false);assert.equal(h.playCalls,1);h.cleanup()});
test('blocked autoplay also holds and finishes once without wrapping',async()=>{const h=heroHarness({blocked:true});h.ready();await Promise.resolve();await Promise.resolve();h.at(6.78);h.advance(40);h.advance(40);assert.equal(h.video.currentTime,6.8);h.seeked();h.advance(40);assert.equal(h.frames.size,0);h.progress(.1);h.at(7.94);h.advance(40);h.advance(40);assert.ok(h.video.currentTime>=7.94);h.seeked();h.advance(40);assert.equal(h.frames.size,0);const time=h.video.currentTime;h.progress(0);h.progress(1);h.advance(4000);assert.equal(h.video.currentTime,time);h.cleanup();assert.equal(h.timers.size,0)});
test('reduced motion loads no video, and visibility pauses then automatically resumes',async()=>{const h=heroHarness({reduced:true});assert.equal(h.video.src,'');assert.equal(h.states[1],true);assert.equal(h.playCalls,0);h.cleanup();const v=heroHarness();v.ready();await Promise.resolve();v.document.hidden=true;v.document.dispatchEvent(new Event('visibilitychange'));assert.equal(v.video.paused,true);assert.equal(v.frames.size,0);v.document.hidden=false;v.document.dispatchEvent(new Event('visibilitychange'));assert.equal(v.video.paused,false);await Promise.resolve();v.intersect(false);assert.equal(v.video.paused,true);v.intersect(true);assert.equal(v.video.paused,false);v.cleanup()});
test('phone rotation does not replace the selected video source',()=>{const h=heroHarness();const src=h.video.src;h.window.dispatchEvent(new Event('resize'));assert.equal(h.video.src,src);h.cleanup()});
