'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,MessageCircle} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {privateSearchWhatsApp,type CarPreferences} from '@/lib/private-search';
const questions=[{key:'brand',title:'Which marque speaks to you?',hint:'A favourite brand. Or a world of possibilities.',options:['Lamborghini','Ferrari','Porsche','Mercedes-Benz','BMW','Bentley','Rolls-Royce','McLaren','Land Rover','Audi','Another brand','No preference']},{key:'budget',title:'What range feels right?',hint:'Your preferred budget, in US dollars.',options:['Under $50,000','$50,000–$100,000','$100,000–$200,000','$200,000–$350,000','$350,000+','Flexible']},{key:'body',title:'How do you imagine the drive?',hint:'Choose the silhouette that suits you.',options:['Coupe','Convertible','SUV','Sedan','No preference']},{key:'year',title:'Which era is yours?',hint:'Choose a preferred model year or range.',options:['2024 or newer','2020–2023','2015–2019','Before 2015','No preference']},{key:'message',title:'Anything else on your wish list?',hint:'A model, a colour, a detail that matters. Optional.',options:[]} ] as const;
const empty:CarPreferences={brand:'',budget:'',body:'',year:'',message:''};
export default function FindMyCar(){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[answers,setAnswers]=useState<CarPreferences>(empty),[otherBrand,setOtherBrand]=useState('');
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(open)heading.current?.focus({preventScroll:true})},[step,open]);
 const question=questions[step];
 const complete=step===5;
 const ready=complete||step===4||Boolean(answers[question.key])&&(step!==0||answers.brand!=='Another brand'||Boolean(otherBrand.trim()));
 const preferences={...answers,brand:answers.brand==='Another brand'?otherBrand.trim():answers.brand};
 function choose(value:string){if(question)setAnswers(current=>({...current,[question.key]:value}))}
 return <section className="private-search section" id="find-my-car" aria-labelledby="private-search-heading"><div><p className="eyebrow">CAN’T FIND YOUR CAR?</p><h2 id="private-search-heading">Tell us what<br/><em>you’re looking for.</em></h2><p className="private-search-intro">Our team will help you find the right vehicle.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger className="button outline private-search-trigger">START PRIVATE SEARCH <ArrowRight size={18}/></DialogTrigger><DialogContent className="private-search-dialog"><DialogTitle className="private-search-label">FIND MY CAR <span>PRIVATE CONCIERGE</span></DialogTitle><DialogDescription className="sr-only">Five short questions to prepare your preferences for our sales team on WhatsApp.</DialogDescription><div className="search-progress" aria-label={complete?'Your preferences are ready':`Step ${step+1} of 5`}>{questions.map((q,i)=><span key={q.key} className={i<=step?'is-complete':''}/>)}</div><div className="search-screen" key={step}><p className="eyebrow search-step">{complete?'YOUR PRIVATE SEARCH':`${String(step+1).padStart(2,'0')} / 05`}</p><h3 ref={heading} tabIndex={-1}>{complete?'Let’s find your next car.':question.title}</h3><p className="search-hint">{complete?'Your preferences, ready for a conversation with our team.':question.hint}</p>
 {complete?<dl className="search-summary">{(['brand','budget','body','year'] as const).map((key,i)=><div key={key}><dt>{['Brand','Budget · USD','Body style','Year'][i]}</dt><dd>{preferences[key]}<button onClick={()=>setStep(i)} aria-label={`Edit ${key}`}>Edit</button></dd></div>)}{preferences.message.trim()&&<div><dt>Your message</dt><dd>{preferences.message}<button onClick={()=>setStep(4)} aria-label="Edit message">Edit</button></dd></div>}</dl>:step===4?<textarea className="search-message" aria-label="Optional message" placeholder="Perhaps a particular model, colour or specification…" value={answers.message} maxLength={1000} rows={5} onChange={event=>choose(event.target.value)}/>:<><fieldset className={`search-choices ${step===0?'brand-choices':''}`}><legend className="sr-only">{question.title}</legend>{question.options.map(value=><label key={value} className={answers[question.key]===value?'is-selected':''}><input type="radio" name={`private-search-${question.key}`} value={value} checked={answers[question.key]===value} onChange={()=>choose(value)}/><span>{value}</span>{answers[question.key]===value&&<Check size={14} aria-hidden="true"/>}</label>)}</fieldset>{step===0&&answers.brand==='Another brand'&&<input className="search-other" aria-label="Preferred brand name" placeholder="Your preferred brand" maxLength={80} value={otherBrand} onChange={event=>setOtherBrand(event.target.value)}/>}</>}
 </div><div className="search-actions">{step>0?<button className="text-link search-back" onClick={()=>setStep(current=>current-1)}><ArrowLeft size={16}/> Back</button>:<span/>}{complete?<a className="button search-whatsapp" href={privateSearchWhatsApp(preferences)} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> Continue with Sales on WhatsApp <ArrowUpRight size={16}/></a>:<button className="button" disabled={!ready} onClick={()=>setStep(current=>Math.min(5,current+1))}>{step===4?'Review preferences':'Continue'} <ArrowRight size={17}/></button>}</div></DialogContent></Dialog></section>;
}
