'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,MessageCircle} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {privateSearchWhatsApp,type CarPreferences} from '@/lib/private-search';
import {findCarMatches,type SearchCar} from '@/lib/car-matches';
const questions=[{key:'brand',title:'Which marque speaks to you?',hint:'A favourite brand. Or a world of possibilities.',options:['Lamborghini','Ferrari','Porsche','Mercedes-Benz','BMW','Bentley','Rolls-Royce','McLaren','Land Rover','Audi','Another brand','No preference']},{key:'budget',title:'What range feels right?',hint:'Your preferred budget, in US dollars.',options:['Under $50,000','$50,000–$100,000','$100,000–$200,000','$200,000–$350,000','$350,000+','Flexible']},{key:'body',title:'How do you imagine the drive?',hint:'Choose the silhouette that suits you.',options:['Coupe','Convertible','SUV','Sedan','No preference']},{key:'year',title:'Which era is yours?',hint:'Choose a preferred model year or range.',options:['2024 or newer','2020–2023','2015–2019','Before 2015','No preference']},{key:'message',title:'Anything else on your wish list?',hint:'A model, a colour, a detail that matters. Optional.',options:[]} ] as const;
const empty:CarPreferences={brand:'',budget:'',body:'',year:'',message:''};
export default function FindMyCar({cars}:{cars:SearchCar[]}){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),[answers,setAnswers]=useState<CarPreferences>(empty),[otherBrand,setOtherBrand]=useState('');
 const [matchLimit,setMatchLimit]=useState(3);
 useEffect(()=>{setMatchLimit(3)},[answers,otherBrand]);
 const heading=useRef<HTMLHeadingElement>(null);
 const opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{
  const show=(event:Event)=>{event.preventDefault();opener.current=(event as CustomEvent<HTMLElement>).detail;setOpen(true)};
  document.addEventListener('open-find-my-car',show);
  const url=new URL(location.href);
  if(url.searchParams.get('find-car')==='1'){
   opener.current=document.querySelector<HTMLElement>('[data-find-car]');setOpen(true);
   url.searchParams.delete('find-car');history.replaceState(history.state,'',url.pathname+url.search+url.hash);
  }
  return()=>document.removeEventListener('open-find-my-car',show);
 },[]);
 useEffect(()=>{if(open)heading.current?.focus({preventScroll:true})},[step,open]);
 const question=questions[step];
 const complete=step===5;
 const ready=complete||step===4||Boolean(answers[question.key])&&(step!==0||answers.brand!=='Another brand'||Boolean(otherBrand.trim()));
 const preferences={...answers,brand:answers.brand==='Another brand'?otherBrand.trim():answers.brand};
 const matches=complete?findCarMatches(cars,preferences):[];
 function choose(value:string){if(question)setAnswers(current=>({...current,[question.key]:value}))}
 return <section className="private-search section" id="find-my-car" aria-labelledby="private-search-heading"><div><p className="eyebrow">CAN’T FIND YOUR CAR?</p><h2 id="private-search-heading">Tell us what<br/><em>you’re looking for.</em></h2><p className="private-search-intro">Our team will help you find the right vehicle.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger onClick={()=>{opener.current=null}} className="button outline private-search-trigger">START PRIVATE SEARCH <ArrowRight size={18}/></DialogTrigger><DialogContent finalFocus={()=>opener.current || true} className="private-search-dialog"><DialogTitle className="private-search-label">FIND MY CAR <span>PRIVATE CONCIERGE</span></DialogTitle><DialogDescription className="sr-only">Five short questions to prepare your preferences for our sales team on WhatsApp.</DialogDescription><div className="search-progress" aria-label={complete?'Your preferences are ready':`Step ${step+1} of 5`}>{questions.map((q,i)=><span key={q.key} className={i<=step?'is-complete':''}/>)}</div><div className="search-screen" key={step}><p className="eyebrow search-step">{complete?'YOUR PRIVATE SEARCH':`${String(step+1).padStart(2,'0')} / 05`}</p><h3 ref={heading} tabIndex={-1}>{complete?'Let’s find your next car.':question.title}</h3><p className="search-hint">{complete?'Your preferences, ready for a conversation with our team.':question.hint}</p>
 {complete?<details className="preferences-review"><summary>Review or edit your preferences</summary><dl className="search-summary">{(['brand','budget','body','year'] as const).map((key,i)=><div key={key}><dt>{['Brand','Budget · USD','Body style','Year'][i]}</dt><dd>{preferences[key]}<button onClick={()=>setStep(i)} aria-label={`Edit ${key}`}>Edit</button></dd></div>)}{preferences.message.trim()&&<div><dt>Your message</dt><dd>{preferences.message}<button onClick={()=>setStep(4)} aria-label="Edit message">Edit</button></dd></div>}</dl></details>:step===4?<textarea className="search-message" aria-label="Optional message" placeholder="Perhaps a particular model, colour or specification…" value={answers.message} maxLength={1000} rows={5} onChange={event=>choose(event.target.value)}/>:<><fieldset className={`search-choices ${step===0?'brand-choices':''}`}><legend className="sr-only">{question.title}</legend>{question.options.map(value=><label key={value} className={answers[question.key]===value?'is-selected':''}><input type="radio" name={`private-search-${question.key}`} value={value} checked={answers[question.key]===value} onChange={()=>choose(value)}/><span>{value}</span>{answers[question.key]===value&&<Check size={14} aria-hidden="true"/>}</label>)}</fieldset>{step===0&&answers.brand==='Another brand'&&<input className="search-other" aria-label="Preferred brand name" placeholder="Your preferred brand" maxLength={80} value={otherBrand} onChange={event=>setOtherBrand(event.target.value)}/>}</>}
 {complete&&<section className="search-matches" aria-labelledby="search-matches-heading"><h4 id="search-matches-heading">{matches.length?`${matches.length===1?'A car':`${matches.length} cars`} you may like.`:'Let us find it for you.'}</h4>{matches.length?<><p className="search-hint">Already in our collection. Explore a car, or continue with sales.</p><div className="search-match-list">{matches.slice(0,matchLimit).map(({car,budgetUnconfirmed})=><a key={car.id} href={`/vehicles/${car.id}`} target="_blank" rel="noopener noreferrer" className="search-match"><img src={car.image_url} alt={`${car.make} ${car.model}`} width={88} height={70} loading="lazy"/><span><strong>{car.make} {car.model}</strong><span>{car.year} · {car.price?`USD ${car.price.toLocaleString('en-US')}`:'Price on request'}</span><span className={`match-budget ${budgetUnconfirmed?'unconfirmed':'confirmed'}`}>{budgetUnconfirmed?'Suggestion · budget to confirm':preferences.budget==='Flexible'?'Matches your preferences':'Within your selected budget · listed price'}</span><span className="search-match-link">View car ↗ <span className="sr-only">(opens in a new tab)</span></span></span></a>)}</div>{matches.length>matchLimit&&<button className="text-link search-more" onClick={()=>setMatchLimit(value=>value+3)}>Show more ({matches.length-matchLimit}) <ArrowRight size={15}/></button>}<p className="search-match-note">Matches use brand, budget, body style and year. Sales can confirm availability and any extra requests.</p></>:<p className="search-hint">No listed car matches these selections right now. Share your preferences on WhatsApp and our team will help.</p>}</section>}
 </div><div className={`search-actions ${complete?'has-matches':''}`}>{step>0?<button className="text-link search-back" onClick={()=>setStep(current=>current-1)}><ArrowLeft size={16}/> Back</button>:<span/>}{complete?<a className="button search-whatsapp" href={privateSearchWhatsApp(preferences)} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> Continue with Sales on WhatsApp <ArrowUpRight size={16}/></a>:<button className="button" disabled={!ready} onClick={()=>setStep(current=>Math.min(5,current+1))}>{step===4?'Review preferences':'Continue'} <ArrowRight size={17}/></button>}</div></DialogContent></Dialog></section>;
}
