'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {ArrowLeft,ArrowRight,Play,Pause,MoveHorizontal,RotateCw,LoaderCircle} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import ExteriorTour from './exterior-tour';
const wrap=(value:number)=>((value%1)+1)%1;
export default function VideoTour({src,photos,title}:{src:string;photos:string[];title:string}){
 const video=useRef<HTMLVideoElement>(null),frame=useRef(0),current=useRef(0),target=useRef(0),last=useRef(0),play=useRef(false),reduce=useRef(false);
 const drag=useRef<{id:number;x:number;position:number;width:number}|null>(null);
 const [ready,setReady]=useState(false),[failed,setFailed]=useState(false),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[dragging,setDragging]=useState(false);
 function sync(){const v=video.current;if(!v||v.readyState<2||v.seeking||!Number.isFinite(v.duration))return;const time=wrap(current.current)*Math.max(0,v.duration-.05);if(Math.abs(v.currentTime-time)>.035)v.currentTime=time}
 function tick(time:number){frame.current=0;const dt=last.current?Math.min(50,time-last.current):16;last.current=time;if(play.current)target.current+=dt/14000;current.current=reduce.current?target.current:current.current+(target.current-current.current)*(1-Math.exp(-dt/80));if(Math.abs(target.current-current.current)<.00005)current.current=target.current;sync();setPosition(wrap(current.current));if(play.current||current.current!==target.current)frame.current=requestAnimationFrame(tick)}
 function wake(){if(!frame.current){last.current=0;frame.current=requestAnimationFrame(tick)}}
 function seek(value:number){play.current=false;setPlaying(false);target.current=value;wake()}
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{reduce.current=media.matches;if(media.matches){play.current=false;setPlaying(false)}};const hidden=()=>{if(document.hidden){play.current=false;setPlaying(false)}};change();media.addEventListener('change',change);document.addEventListener('visibilitychange',hidden);return()=>{cancelAnimationFrame(frame.current);media.removeEventListener('change',change);document.removeEventListener('visibilitychange',hidden)}},[]);
 useEffect(()=>{if(failed){play.current=false;setPlaying(false);cancelAnimationFrame(frame.current);frame.current=0}},[failed]);
 useEffect(()=>{if(ready||failed)return;const timeout=setTimeout(()=>setFailed(true),12000);return()=>clearTimeout(timeout)},[ready,failed]);
 function start(event:PointerEvent<HTMLDivElement>){if(!ready||!event.isPrimary||event.button!==0)return;seek(current.current);drag.current={id:event.pointerId,x:event.clientX,position:current.current,width:event.currentTarget.clientWidth};event.currentTarget.setPointerCapture(event.pointerId);event.currentTarget.focus({preventScroll:true});setDragging(true)}
 function move(event:PointerEvent<HTMLDivElement>){const d=drag.current;if(d?.id===event.pointerId)seek(d.position-(event.clientX-d.x)/Math.max(d.width,1))}
 function stop(event:PointerEvent<HTMLDivElement>){if(drag.current?.id!==event.pointerId)return;drag.current=null;setDragging(false);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)}
 if(failed)return <><p className="availability">The animation could not load. Explore the original exterior photographs below.</p><ExteriorTour photos={photos} title={title}/></>;
 return <div className="animated-tour"><div className={`photo-stage tour-stage animated-tour-stage ${dragging?'is-dragging':''}`} role="group" tabIndex={0} aria-label={`${title} AI animated exterior tour`} aria-busy={!ready} onPointerDown={start} onPointerMove={move} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={()=>{drag.current=null;setDragging(false)}} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();seek(event.key==='Home'?0:event.key==='End'?.999:target.current+(event.key==='ArrowRight'?.05:-.05))}}}>
 <video ref={video} src={src} muted playsInline preload="auto" onLoadedData={()=>{setReady(true);sync()}} onSeeked={sync} onError={()=>setFailed(true)} aria-hidden="true"/><span className="tour-badge"><RotateCw size={15}/> ANIMATED EXTERIOR</span>{!ready?<div className="photo-status" role="status"><LoaderCircle className="photo-loader" size={22}/><span>Preparing your animated tour…</span></div>:<div className="drag-hint"><MoveHorizontal size={20}/><span>{dragging?'EXPLORING':'DRAG TO TURN THE CAR'}</span></div>}</div>
 <div className="gallery-controls exterior-controls"><button disabled={!ready} aria-label="Turn left" onClick={()=>seek(target.current-.08)}><ArrowLeft size={20}/></button><button className="tour-play" disabled={!ready} onClick={()=>{play.current=!play.current;setPlaying(play.current);wake()}}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'Pause tour':'Play tour'}</button><button disabled={!ready} aria-label="Turn right" onClick={()=>seek(target.current+.08)}><ArrowRight size={20}/></button></div><div className="tour-controls"><p><MoveHorizontal size={18}/><span>Drag or swipe in either direction. Pause at any angle.</span></p><Slider aria-label="Exterior animation position" disabled={!ready} min={0} max={.999} step={.001} value={[position]} onValueChange={value=>seek(Array.isArray(value)?value[0]:value)}/><p className="tour-disclosure">AI visualization by Higgsfield, based on this vehicle’s photographs. Unphotographed angles are reconstructed and may differ from the actual car. See Gallery for original photos.</p></div></div>;
}
